### ISSUE TITLE
Processing stopped during the rdrdem_offset stage

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/isce2#239]
I've processed ALOS-2 stripmap images to generate DInSAR images using the alos2App.py. Then, during the rdrdem_offset stage an error occurred halting the data processing. I've attached the screenshot of the error message for reference. I've used the latest version of ISCE2 and compiled it using CMake for this. I've also processed the images using the Conda version of ISCE2 and it processed flawlessly.
<img width="1680" alt="error" src="https://user-images.githubusercontent.com/21336508/109082063-34a77700-773e-11eb-852f-2f30c487e074.png">

**Comment by rtburns-jpl** [comment]
> I've also processed the images using the Conda version of ISCE2 and it processed flawlessly

Interesting - that means the issue is somewhere in here: https://github.com/isce-framework/isce2/compare/v2.4.2...7bb66ec7823de4e86ec425ddd8e22501ea6c21c5. Do you think you could do a `git bisect` on that range?

**Comment by bjmarfito** [comment]
I've ran git bisect. I don't know if this should be the result. I am posting the screenshot of the result.
<img width="499" alt="git_bisect" src="https://user-images.githubusercontent.com/21336508/109111194-6f77d200-7773-11eb-9bd2-4a5f3beacff4.png">

**Comment by rtburns-jpl** [comment]
Nice, now that you specified the good and bad commits, it checked out the middle of that range, https://github.com/isce-framework/isce2/commit/29bf14c518652743b334b3c14547b5f83caa809d. So now you rerun the workflow, and tell it `git bisect good` or `git bisect bad` based on the result. If you keep doing that, eventually git will tell you the commit that broke the code - it says there are 20 commits in the range, so it will take about 4 tries to pin it down.

**Comment by bjmarfito** [comment]
Do I need to recompile ISCE2 again or I just need to run alos2App.py?

**Comment by rtburns-jpl** [comment]
Yes, you'll need to rebuild at each bisect step.

**Comment by bjmarfito** [comment]
I'm attaching the result after running the steps four times.
<img width="568" alt="result" src="https://user-images.githubusercontent.com/21336508/109117011-5b849e00-777c-11eb-924d-162c0fbad694.png">

**Comment by rtburns-jpl** [comment]
Ok, I think it needs one more bisect step, and then it will tell you 'so-and-so is the first bad commit'

**Comment by bjmarfito** [comment]
This is the result after running it. This time ISCE2 failed to compile.
<img width="1680" alt="final_result" src="https://user-images.githubusercontent.com/21336508/109118045-c1255a00-777d-11eb-9489-51d4a703c123.png">

**Comment by rtburns-jpl** [comment]
Oh hmm, hopefully the compilation error isn't a confounding factor here. I'll take a look at this, thanks for running through the bisect with me.

**Comment by bjmarfito** [comment]
You're welcome. Thank you also for addressing this issue.

**Comment by rtburns-jpl** [comment]
Ok, to be clear, if you try to test on commit https://github.com/isce-framework/isce2/commit/a393282b6923507623b713295c9385fb1958463c, do you get an error when building isce2? Those 'duplicate symbols' errors were supposed to be resolved by my commit which is reported as the first 'bad' one, so I'm a little confused if the bisection worked properly.

**Comment by bjmarfito** [comment]
I've run git bisect again. Unfortunately, the same issue as before.

Below are the procedures that I've did. Kindly check if there are any mistakes on the procedures. Thanks!

1. Changed directory to isce2
2. Initialized git bisect by typing git bisect start on the terminal
3. Tagged v2.4.2 as a good version by typing git bisect good
4. Tagged the current build as a bad version by typing git bisect bad
5. Remove previous build directory by typing rm -rf build
6. Create new build directory by typing mkdir build && cd build
7. Initialize cmake by typing the ff on the terminal:
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DPYTHON_MODULE_DIR=lib/python3.8/site-packages -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DCMAKE_FIND_FRAMEWORK=NEVER -DOpenMP_C_FLAGS=-fopenmp=lomp -DOpenMP_CXX_FLAGS=-fopenmp=lomp -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_libomp_LIBRARY="/Users/bryanmarfito/miniconda3/envs/isce2expe/lib/libomp.dylib" -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp /Users/bryanmarfito/miniconda3/envs/isce2expe/lib/libomp.dylib -I/Users/bryanmarfito/miniconda3/envs/isce2expe/include" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp /Users/bryanmarfito/miniconda3/envs/isce2expe/lib/libomp.dylib -I/Users/bryanmarfito/miniconda3/envs/isce2expe/include"
8. Compile the codes by typing the make
9. Installed the compiled codes by typing make install
10. Run the workflow by typing alos2App.py –start=startup
11. If the errors persist, run steps 4 to 10.
12. If not, type git bisect good.

**Comment by rtburns-jpl** [comment]
Hmm, well I guess the part I left out is that you need to `git bisect skip` any steps which give you a _different_ error from the original FileNotFoundError we're trying to pin down. So for example, those 'duplicate symbol' compilation errors probably should have warranted a 'skip' since the code didn't build - so we're not sure whether alos2App.py still had the offset issue at that point.

**Comment by bjmarfito** [comment]
Yes, I've run git bisect skip as you've suggested. Below is the screenshot of the result.
<img width="1680" alt="error_2" src="https://user-images.githubusercontent.com/21336508/109252048-8f68cd80-7827-11eb-822a-91b1de697343.png">

**Comment by rtburns-jpl** [comment]
Can you try to build this branch, and see if it fixes your issue?
https://github.com/rtburns-jpl/isce2/tree/fix-alos-reader

**Comment by bjmarfito** [comment]
I've built and run your isce2 repo. Unfortunately, it didn't fix the issue. Same error as with before. Pls. see the screenshot below.

<img width="1680" alt="error_3" src="https://user-images.githubusercontent.com/21336508/109254634-64817800-782d-11eb-9466-f9672c237871.png">

**Comment by rtburns-jpl** [comment]
Well, I'm stumped. Is it possible for me to reproduce this error with ALOS1 data? Or will I need to go find some ALOS2 data to test on?

**Comment by bjmarfito** [comment]
Currently, I'm running it using LinuxOS. I'll update you on the progress.

**Comment by bjmarfito** [comment]
I've used the isce framework repo of isce2 and your repo of isce2. The same error occurs even in Linux. I've attached the screenshot of the error.

![error_linux](https://user-images.githubusercontent.com/21336508/109276116-96580600-7850-11eb-93b2-664408340a61.JPG)
